### ISSUE TITLE
Add url to asset when serialize to JSON

### ISSUE THREAD

**Issue by yulapshun** [SkygearIO/skygear-SDK-JS#10]
Currently formJSON() of asset has url, but toJSON() remove the url. So a deserialize asset cannot be serialized to its original form.

**Comment by rickmak** [comment]
The intention of trim the url at `toJSON` is because of `skygear-server` don't accept asset with `url`. Since it set the wrong expectation to user, i.e. the server can download a remote image url.

The usage of `toJSON` for application caching is completely valid. And the SDK should try our best to return identical object when the user calling `fromJSON`.

The solution will be move the trim logic to the actual API call, not couple with the skygear record.
