### ISSUE TITLE
deleteRecordWithID will crash if no permission to delete

### ISSUE THREAD

**Issue by cpandrewchung** [SkygearIO/skygear-SDK-JS#20]
it will throw exception if no permission to delete the record.
Also, suggest the record (like conversation) can be delete if the user is admin. (now only owner can delete)

**Comment by rickmak** [comment]
As per our discussion over chat room. This issue is addressed here: https://github.com/SkygearIO/skygear-SDK-iOS/commit/66926609c28d51437ade111d4d0861b5ac458b27

And we have released `0.12.1`(https://github.com/SkygearIO/skygear-SDK-iOS/releases/tag/0.12.1)  that can install via cocoapods(https://cocoapods.org/pods/SKYKit)
