### ISSUE TITLE
Auto build and upload min js to cloudfront in release script

### ISSUE THREAD

**Issue by royuen** [SkygearIO/skygear-SDK-JS#21]

**Comment by cheungpat** [comment]
If no one has a problem, the js file will be accessible from something like:
* `https://code.skygear.io/js/skygear-latest.min.js`
* `https://code.skygear.io/js/skygear-0.12.0.min.js`.

**Comment by cheungpat** [comment]
On second thought, I changed the URL to the followings:

* https://code.skygear.io/js/skygea/latest/skygear.min.js
* https://code.skygear.io/js/skygear/0.12.0/skygear.min.js.

It is because:

* This is how cdnjs do
* The min.js file has a path pointing to the source map which we need to replace if we use the former naming
* The code to rename the upload path is simpler.

**Comment by royuen** [comment]
Sure, the latest one not uploaded yet?
