### ISSUE TITLE
Upload asset without also saving a record

### ISSUE THREAD

**Issue by cheungpat** [SkygearIO/skygear-SDK-JS#267]
This is a feature request: In CMS, asset is uploaded when the user select a file from the file picker. The user may decide to save the record with the new asset or the user may abort and not save anything at all.

This function is previously exposed by `skygear.makeUploadAssetRequest` which is now marked internal in version 1.0.0. To support the CMS use case, I suggest we create a `skygear.publicDatabase.uploadAsset` to upload an asset without also trigger a record save.

**Comment by rickmak** [comment]
I am wondering should the upload Asset belong to publicDatabase. Feel like we should have a `skygaer.asset.upload`.


Because publicDatabase is only record related, putting asset to this grouping is no good. In addition, the publicity of a asset is control by setting rather than by publicDatabase/privateDatabase. So it worth to make a new group `asset`. also it give hit to developer he can use skygear as asset store just as s3.

**Comment by cheungpat** [comment]
The `uploadAsset` function is best contained in `DatabaseContainer` (which is not `PublicDatabase` nor `PrivateDatabase`) but it this container is not exposed by Container. 

I could create a `DatabaseContainer` by `new skygear.DatabaseContainer(container)` and then execute the `uploadAsset` function from there, if we decide this is not a common use case.
