### ISSUE TITLE
Unable to save record asset after adding record before save

### ISSUE THREAD

**Issue by carmenlau** [SkygearIO/skygear-SDK-JS#405]
(Describe the issue here)

- Skygear SDK Date/Version:
- JS runtime:
- Skygear Server Date/Version:
- [ ] Is this a regression?
- [ ] Attached logs, screenshots

#### Server log
```
{
    "result": [
        {
            "_id": "article/<id>",
            "_type": "error",
            "code": 10000,
            "message": "Failed to parse plugin response: invalid character 'I' looking for beginning of value",
            "name": "UnexpectedError"
        }
    ]
}
```

**Comment by cheungpat** [comment]
The reason this is happening is because:

* skygear-server sometimes inject signer asset before calling database hooks and sometimes it doesn’t
* the JS SDK expect the Asset to be used by developer, hence it has more checking on parameter than py-skygear counterpart.

To fix this,

* skygear-server should inject signer each time it calls before hooks

It is also possible to fix this on the JS side by relaxing checking on Asset constructor parameter.

**Comment by carmenlau** [comment]
Handled in https://github.com/SkygearIO/skygear-server/issues/567
