### ISSUE TITLE
pubsub should have a retry connection options

### ISSUE THREAD

**Issue by chpapa** [SkygearIO/skygear-SDK-JS#52]
Was inspired by this commit: https://github.com/oursky/doorlock/commit/ba23e9958cf0146fd24b6bdf3be6e8b2939d0a54

The developer in the above commit has to explicitly re-subscribe to a channel onConnectionClose()

The SDK maybe should have a default retry value and / or infinity by default?

**Comment by royuen** [comment]
Right now the SDK will reconnect automatically when the pubsub was being disconnected, there is also no specific retry count so it is infinite.

Developer doesn't need to handle retry manually in the code.

After discussion with @Steven-Chan, learnt that the cause was that there was no manual retry code in the beginning until the doorlock was being disconnected over the night and not being reconnected. So we believe there is problem in the current reconnect mechanism.

Following actions should be made:

- Setup a testing service to try reproducing the error, with adequate log, to be done by @rickmak 
- Review the doc and propose update to explain auto reconnect mechanism, to be done by @royuen

**Comment by chpapa** [comment]
Thanks! So it sounds more like a bug and no change would be needed on the
SDK interface.

**Comment by royuen** [comment]
Doc updated in https://github.com/SkygearIO/skygear-doc/pull/305
