### ISSUE TITLE
skygear.on() should avoid multiple subscription on the same handler

### ISSUE THREAD

**Issue by jasonkit** [SkygearIO/skygear-SDK-JS#53]
To pay safe, skygear.on() should first check whether the handler exists in the handler list before adding it to the list.

**Comment by rickmak** [comment]
``` js
const EventEmitter = require('events');

const ee = new EventEmitter();

function handler1() {
  console.log('1');
}

function handler2() {
  console.log('2');
}

ee.on('trigger', handler1);
ee.on('trigger', handler1);
ee.on('trigger', handler2);
ee.emit('trigger');
```

The above program output will be 
```
1
1
2
```

After discussion with @jasonkit and @limouren and with above example, everyone agree that `skygear.on()` can allow multiple subscription on the same handler function to avoid confusion with the EventEmitter come with the languages.

Since the original of this issue is skygear help people to re-subscribe automatically. But not clearly state in the https://docs.skygear.io/js/guide/pubsub . So proper resolution will be a polish of documentation.
