### ISSUE TITLE
Upgrade to use babel6

### ISSUE THREAD

**Issue by rickmak** [SkygearIO/skygear-SDK-JS#69]
### Related issue: 

1. [Compatibility issue of localforage](https://github.com/SkygearIO/skygear-SDK-JS/issues/39)
2. [SDK not working on IE10 due to "extend Array" using Array.form](https://github.com/SkygearIO/skygear-SDK-JS/issues/66)

**Comment by ben181231** [comment]
### Findings when working on [Issue 66](https://github.com/SkygearIO/skygear-SDK-JS/issues/66)

- Need to update all babel related packages to `v6+`
- Extra presents (e.g. "es2015", "stage-2", etc.) need to be installed, since Babel 6 will not include them by default, according to [this guide](https://babeljs.io/blog/2015/10/31/setting-up-babel-6).
- `npm run test` fails since some of the sub tasks in `pre-test` reads the `.babelrc` and cannot recognize `presets` property.
